# Generated by Django 5.1 on 2024-09-09 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='last_updated',
        ),
    ]
