# Generated by Django 5.1 on 2024-09-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_comment_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked_at',
        ),
        migrations.AddField(
            model_name='like',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
