# Generated by Django 5.1 on 2024-09-10 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_like_liked_at_like_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='count',
            new_name='total_likes',
        ),
    ]
